### ISSUE TITLE
Framework Addition possibility - Backpack On Chest (BOC)

### ISSUE THREAD

**Issue by Aethoriago** [TaskForceDingo/2019-Mission-Framework#14]
Will require a strip down from a mod format to a script for framework addition, but would give players functionality to carry backpacks on legs, leading to modern airborne missions being more able to be run. If not able to be stripped down can be added as a mod (as below) to the modset. Required mods are CBA and ACE3, ones already in the modset so integration is seamless.

Mod steam found here:
`https://steamcommunity.com/sharedfiles/filedetails/?id=820924072`
Mod Github found below:
`https://github.com/DerZade/BackpackOnChest`

Cheers for referring me to submitting this Johnny, and good luck.

**Comment by Aethoriago** [comment]
This would work well, and honestly another mod like this
`https://steamcommunity.com/sharedfiles/filedetails/?id=1334412770`
could be included as well, either as a framework script or as an addition to the modset.

**Comment by TheTimidShade** [comment]
Ported into framework, tested in SP and dedicated environment. Pending admin approval to integrate into master copy.
