### ISSUE TITLE
Feature Addition Smoke

### ISSUE THREAD

**Issue by TaskForceDingo** [TaskForceDingo/2019-Mission-Framework#15]
Adding a smoke effect on DAC AI artillery call as a pre warning system for Arty being called on player. Similar to what Ton had in his Crimson Trail mission.

Eg. DAC AI calls for support - Support Fail - No smoke on call location.
DAC AI calls for support - Support Success - smoke on call location - Arty Strikes

**Comment by TheTimidShade** [comment]
DAC no longer supported
