### ISSUE TITLE
Admin panel teleport button state displayed incorrectly

### ISSUE THREAD

**Issue by TheTimidShade** [TaskForceDingo/2019-Mission-Framework#24]
The teleport button on the admin panel seems to show the incorrect state when toggled, displays yellow when teleport is off, white when teleport is on, only displays correctly when panel is first opened

Not sure if this is an issue on my end or not, but seems to happen with fresh adminpanel from framework
![20191020191744_1](https://user-images.githubusercontent.com/52023652/67157085-71a37280-f36e-11e9-993b-0a43c0a4b2ed.jpg)
![20191020191750_1](https://user-images.githubusercontent.com/52023652/67157086-71a37280-f36e-11e9-953f-141a8fc8f419.jpg)

**Comment by TaskForceDingo** [comment]
Happens occasionally to me but functionality remains

**Comment by TheTimidShade** [comment]
Yeah it's no big issue by any means but thought I'd post it here anyway because it's something @JohnnyShootos could probably fix rather easily anyway

**Comment by TheTimidShade** [comment]
Not relevant in latest admin panel
