### ISSUE TITLE
licenses 

### ISSUE THREAD

**Issue by YonVclaw** [TaskForceDingo/2019-Mission-Framework#71]
May I inquire about the licenses on the code in this repo ?

**Comment by TaskForceDingo** [comment]
What do you want to know?

**Comment by YonVclaw** [comment]
If it's opensource, I would like to use the admin panel to replace the one my group is currently using.
As busy work I want to make our missions a bit more useable by folks on steam. To do that I need to move a lot of functions from our custom mod to the mission, to remove the custom mod as a dependency.

**Comment by TaskForceDingo** [comment]
It's all open mate just quote us unless you make a substantial change

**Comment by YonVclaw** [comment]
thank you, I'll credit you group, and orginal authors in the end product
