### ISSUE TITLE
Admin Panel Zeus module unable to remote control AI

### ISSUE THREAD

**Issue by SkilletKid** [TaskForceDingo/2019-Mission-Framework#9]
Zeus remote control function not working with any AI in dedicated environment.

Tested with:
Preplaced AI
DAC spawned AI
Zeus placed AI

Updating edittable objects via ace Zeus function did not help.

**Comment by JohnnyShootos** [comment]
Found issue: did not add the appropriate event handlers to the created Zeus' 

fixed
